
define r = Character("River", color="#80c0e0")
define h = Character("Havana",color="#e19ef0")
define d = Character("Doc", color="#e1e6f7")
define gm = Character("Grandma", color="#94889e")
define gp = Character("Gramps", color="#5c5563")
define i = Character("Info-Kun")
define ls = Character("Local Shaman", color="#ebe783")
define isec = Character("Island Security", color="#3209e6")

define CO2 = Character("CO2") 
define NH4  = Character("NH4")
define NO2 = Character("NO2")
define SF6 = Character("SF6")
define PFC = Character("PFC")
define HFC = Character("HFC")
define NF3 = Character("NF3")